version: '3.9'
services:
  db:
    container_name: SMS-DB
    image: postgres
    environment:
      POSTGRES_DB: sms_inbox_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    container_name: SMS-SERVICE
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/sms_inbox_db
    ports:
      - "5000:5000"
    depends_on:
      - db
